/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: agustin.trezza (https://sketchfab.com/agustin.trezza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-1-e6a5af39d2b3495fb4fb1f8f94d3efda
Title: Javascript (1)
*/
import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

export function JSLogo(props) {
    const jsref= useRef()
    const { nodes, materials } = useGLTF('models/javascript.glb');

    useGSAP(() => {
        gsap.to(jsref.current.position, {
          y: jsref.current.position.y + 1,
          duration: 5,
          repeat: -1,
          yoyo: true,
        });
      });
    
    return (
        <Float floatIntensity={2}>

    <group {...props} dispose={null}>
      <mesh
      ref= {jsref}
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.mat_3220964}
        rotation={[0,0, 90]}  
        scale={0.2}    />
    </group>
    </Float>
  )
}

useGLTF.preload('models/javascript.glb')